version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=efos-checker-user
      - POSTGRES_PASSWORD=efos-checker-password
      - POSTGRES_DB=efos-checker
      - POSTGRES_PORT=5433
volumes:
  data:
